name: Build Yanga CYBORG

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore project
        run: dotnet restore yangaCYBORG.sln

      - name: Build project
        run: dotnet build yangaCYBORG.sln --configuration Release --no-restore
